#---------------------------------#
#      general configuration      #
#---------------------------------#

# we use GitVersion to generate official version numbers, so just use the build number by default
# version: {build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# os: Windows Server 2012

#---------------------------------#
#       build configuration       #
#---------------------------------#

# master branch build config
-
  branches:
    only:
      - master

  configuration: Release

  build:
    project: Karbon.Cms.sln
    verbosity: minimal

  before_build:
    - nuget restore

  #---------------------------------#
  #       tests configuration       #
  #---------------------------------#

  after_test:
    - msbuild Package.build.xml /t:Clean;Package

  #---------------------------------#
  #      artifacts configuration    #
  #---------------------------------#

  artifacts:
    - path: Package\*.nupkg

# default build config
-
  configuration: Debug

  build:
    project: Karbon.Cms.sln
    verbosity: minimal

  before_build:
    - nuget restore

  #---------------------------------#
  #       tests configuration       #
  #---------------------------------#

  after_test:
    - msbuild Package.build.xml /t:Clean;Package

  #---------------------------------#
  #      artifacts configuration    #
  #---------------------------------#

  artifacts:
    - path: Package\*.nupkg
